version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "vector_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector-data:
